export const SET_COUNTRY_BEGIN = "SET_COUNTRY_BEGIN";
export const SET_COUNTRY_SUCCESS = "SET_COUNTRY_SUCCESS";
export const SET_COUNTRY_FAILURE = "SET_COUNTRY_FAILURE";
export const SET_COUNTRY_EMPTY = "SET_COUNTRY_EMPTY";
